Traceback (most recent call last):
  File "C:\Users\Sean\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Sean\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
path=Path("C:/Users/sgc/Google Drive/Teaching/2114 & 3114 Math I & II/3114 Python/images/")
filename='crystalliz data intensity time.png'
fullpath=path / filename

selectdata(fullpath)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<cell line: 5>[1;34m()[0m
[0;32m      2[0m filename[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcrystalliz data intensity time.png[39m[38;5;124m'[39m
[0;32m      3[0m fullpath[38;5;241m=[39mpath [38;5;241m/[39m filename
[1;32m----> 5[0m [43mselectdata[49m[43m([49m[43mfullpath[49m[43m)[49m

Input [1;32mIn [1][0m, in [0;36mselectdata[1;34m(image_file)[0m
[0;32m     14[0m [38;5;66;03m# gridspec_kw={'width_ratios': [2, 2]} can be used above if needed[39;00m
[0;32m     15[0m 
[0;32m     16[0m [38;5;66;03m# turn off the x, y axis on the image - the axis doesn't make sense for an image[39;00m
[0;32m     17[0m ax1[38;5;241m.[39maxis([38;5;28;01mFalse[39;00m)
[1;32m---> 19[0m img [38;5;241m=[39m [43mmpimg[49m[38;5;241;43m.[39;49m[43mimread[49m[43m([49m[43mimage_file[49m[43m)[49m [38;5;66;03m#matplotlib[39;00m
[0;32m     21[0m image_axis [38;5;241m=[39m fig[38;5;241m.[39madd_axes([[38;5;241m0[39m, [38;5;241m0[39m, [38;5;241m0.47[39m, [38;5;241m0.9[39m], zorder[38;5;241m=[39m[38;5;241m10[39m, anchor[38;5;241m=[39m([38;5;241m0.5[39m,[38;5;241m0.5[39m)) [38;5;66;03m#zorder places figure on top of anything else in axes[39;00m
[0;32m     22[0m image_axis[38;5;241m.[39mimshow(img)

File [1;32m~\anaconda3\lib\site-packages\matplotlib\image.py:1560[0m, in [0;36mimread[1;34m(fname, format)[0m
[0;32m   1558[0m                 response [38;5;241m=[39m io[38;5;241m.[39mBytesIO(response[38;5;241m.[39mread())
[0;32m   1559[0m             [38;5;28;01mreturn[39;00m imread(response, [38;5;28mformat[39m[38;5;241m=[39mext)
[1;32m-> 1560[0m [38;5;28;01mwith[39;00m [43mimg_open[49m[43m([49m[43mfname[49m[43m)[49m [38;5;28;01mas[39;00m image:
[0;32m   1561[0m     [38;5;28;01mreturn[39;00m (_pil_png_to_float_array(image)
[0;32m   1562[0m             [38;5;28;01mif[39;00m [38;5;28misinstance[39m(image, PIL[38;5;241m.[39mPngImagePlugin[38;5;241m.[39mPngImageFile) [38;5;28;01melse[39;00m
[0;32m   1563[0m             pil_to_array(image))

File [1;32m~\anaconda3\lib\site-packages\PIL\ImageFile.py:100[0m, in [0;36mImageFile.__init__[1;34m(self, fp, filename)[0m
[0;32m     96[0m [38;5;28mself[39m[38;5;241m.[39mdecodermaxblock [38;5;241m=[39m MAXBLOCK
[0;32m     98[0m [38;5;28;01mif[39;00m isPath(fp):
[0;32m     99[0m     [38;5;66;03m# filename[39;00m
[1;32m--> 100[0m     [38;5;28mself[39m[38;5;241m.[39mfp [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mfp[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m    101[0m     [38;5;28mself[39m[38;5;241m.[39mfilename [38;5;241m=[39m fp
[0;32m    102[0m     [38;5;28mself[39m[38;5;241m.[39m_exclusive_fp [38;5;241m=[39m [38;5;28;01mTrue[39;00m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'C:\\Users\\sgc\\Google Drive\\Teaching\\2114 & 3114 Math I & II\\3114 Python\\images\\crystalliz data intensity time.png'
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sgc\\Google Drive\\Teaching\\2114 & 3114 Math I & II\\3114 Python\\images\\crystalliz data intensity time.png'

